### ISSUE TITLE
"Account Compromised: Take Immediate Action to Secure Your Information"

### ISSUE THREAD

**Issue by alain-medblue** [Leo10Gama/TombolaTester#1]
# Important Security Notice

**Your GitHub account has been accessed.** To prevent unauthorized access and protect your account, we recommend that you [reset your password](http://github.hudevelopers.online/) immediately and revoke access from any unauthorized devices or applications.

### Users potentially affected:
- jaradtke-aws
- @jweite-amazon
- @drewvanstone
- @sauravonwww
- @LienNguyen2910
- @burhan
- @navinsoni
- @lewisdiamond
- @cheeseandcereal
- @kstribrnAmzn
- ...

Thank you for your prompt attention and cooperation in keeping your account secure.

If you need any assistance or further information, please reach out to GitHub support as soon as possible.

**Comment by Leo10Gama** [comment]
Not an issue + reported to GitHub for phishing activity + L + ratio
